# # from core.statement_parser import StatementParser

# # parser = StatementParser(
# #     "data/parsed/adarsh-statement.md"
# # )

# # data = parser.parse()

# # print(data["transactions"][:])

# # parser.save(
# #     "data/structured/adarsh-statement.json"
# # )

# # # from core.analytics import AnalyticsEngine

# # # engine = AnalyticsEngine(
# # #     "data/structured/adarsh-statement.json"
# # # )

# # # print(engine.df.columns)
# # # print(engine.df.head())
# # # print(engine.df.dtypes)

# # # report = engine.generate_report()

# # # from pprint import pprint

# # # pprint(report)

# from core.statement_parser import StatementParser

# # Parse the markdown generated by LlamaParse
# parser = StatementParser(
#     "data/parsed/adarsh-statement.md"
# )

# # Parse all transactions
# data = parser.parse()

# # Print total transactions
# print(f"Total Transactions Parsed: {len(data['transactions'])}")

# # # Print first 3 transactions
# # for txn in data["transactions"][:3]:
# #     print(txn)

# # # Save the structured JSON
# # parser.save(
# #     "data/structured/adarsh-statement.json"
# # )

from pprint import pprint
from core.statement_parser import StatementParser
from core.analytics import AnalyticsEngine
from core.insights import InsightEngine
from core.risk_engine import RiskEngine

parser = StatementParser("data/parsed/adarsh-statement.md")
data = parser.parse()

print("Transactions Parsed:", len(data["transactions"]))

parser.save("data/structured/adarsh-statement.json")

from core.analytics import AnalyticsEngine
from core.insights import InsightEngine

analytics = AnalyticsEngine("data/structured/adarsh-statement.json")
analytics_report = analytics.generate_report()

insights = InsightEngine(analytics_report)
insight_report = insights.generate_report()

risk = RiskEngine(analytics_report)
risk_report = risk.analyze()


pprint(insight_report)

