"""
Kotak Mahindra Bank savings account statement parser.

This parser is designed specifically for the HTML/Markdown structure
generated by LlamaParse from Kotak Mahindra Bank / Kotak 811 statements.

Expected transaction table:

    # | TRANSACTION DATE | VALUE DATE | TRANSACTION DETAILS
      | CHQ / REF NO.    | DEBIT/CREDIT(₹) | BALANCE(₹)

The parser converts Kotak's signed transaction amounts into the
canonical representation expected by TransactionNormalizer:

    +100.00 -> CREDIT, 100.00
    -100.00 -> DEBIT, 100.00
"""

from __future__ import annotations

import re
from datetime import datetime

from core.statement_formats.base import BaseStatementParser
from models.enums import BankName


class KotakSavingsParser(BaseStatementParser):
    """
    Parser for Kotak Mahindra Bank savings / Kotak 811 statements.
    """

    # =========================================================
    # Detection
    # =========================================================

    @classmethod
    def matches(cls, text: str) -> bool:
        """
        Determine whether the supplied LlamaParse output
        represents a Kotak savings statement.

        We intentionally require both:

        1. A Kotak-specific signature.
        2. The expected transaction-table structure.

        This prevents a random statement containing the word
        'KKBK' from being incorrectly classified as Kotak.
        """

        text_upper = text.upper()

        kotak_signature = (
            "KOTAK MAHINDRA BANK" in text_upper
            or "KOTAK MAHINDRA BANK LOGO" in text_upper
            or "KOTAK811" in text_upper
            or "KKBK" in text_upper
        )

        statement_structure = (
            "TRANSACTION DATE" in text_upper
            and "VALUE DATE" in text_upper
            and "TRANSACTION DETAILS" in text_upper
            and "DEBIT/CREDIT" in text_upper
            and "BALANCE" in text_upper
        )

        return kotak_signature and statement_structure

    # =========================================================
    # Account
    # =========================================================

    def extract_account(self):
        """
        Populate account-level information available from
        the Kotak statement.

        The supplied sample does not expose reliable account
        holder/account number information, so we only set the
        bank and account type here.
        """

        self.report.account.bank = BankName.KOTAK
        self.report.account.account_type = "Savings"

    # =========================================================
    # Statement Period
    # =========================================================

    def extract_statement_period(self):
        """
        Extract statement period from:

            01 Jul 2026 - 31 Jul 2026
        """

        match = re.search(
            r"(\d{2}\s+[A-Za-z]{3}\s+\d{4})"
            r"\s*-\s*"
            r"(\d{2}\s+[A-Za-z]{3}\s+\d{4})",
            self.text,
        )

        if not match:
            return

        start_text = match.group(1)
        end_text = match.group(2)

        # Keep the existing metadata representation used
        # throughout the project.
        self.report.metadata["statement_period"] = {
            "from": start_text,
            "to": end_text,
        }

        # Also populate the canonical Account fields.
        try:
            self.report.account.statement_start = datetime.strptime(
                start_text,
                "%d %b %Y",
            )

            self.report.account.statement_end = datetime.strptime(
                end_text,
                "%d %b %Y",
            )

        except ValueError:
            pass

    # =========================================================
    # Transaction Table
    # =========================================================

    def _get_transaction_rows(self) -> list[list[str]]:
        """
        Extract transaction rows from the LlamaParse HTML.

        Expected row:

            [
                transaction_number,
                transaction_date,
                value_date,
                transaction_details,
                reference_number,
                signed_amount,
                balance,
            ]

        Kotak statements can span multiple pages. LlamaParse
        represents each page's transaction table separately,
        so we inspect every table.
        """

        rows: list[list[str]] = []

        for table in self.soup.find_all("table"):

            headers = [
                header.get_text(" ", strip=True).upper()
                for header in table.find_all("th")
            ]

            header_text = " ".join(headers)

            # Only process Kotak transaction tables.
            if not (
                "TRANSACTION DATE" in header_text
                and "VALUE DATE" in header_text
                and "TRANSACTION DETAILS" in header_text
                and "DEBIT/CREDIT" in header_text
                and "BALANCE" in header_text
            ):
                continue

            for row in table.find_all("tr"):

                cells = row.find_all("td")

                # Kotak transaction rows contain exactly
                # seven columns.
                if len(cells) != 7:
                    continue

                values = [
                    cell.get_text(" ", strip=True)
                    for cell in cells
                ]

                # First column must be the transaction number.
                if not values[0].isdigit():
                    continue

                # Second column must begin with a Kotak-style date.
                if not re.match(
                    r"^\d{2}\s+[A-Za-z]{3}\s+\d{4}",
                    values[1],
                ):
                    continue

                rows.append(values)

        return rows

    # =========================================================
    # Date Parsing
    # =========================================================

    @staticmethod
    def _parse_transaction_date(value: str) -> str | None:
        """
        Convert Kotak/LlamaParse date into the format expected
        by TransactionNormalizer.

        Input examples:

            19 Jul 2026
            19 Jul 2026 06:36 PM

        Output:

            19-07-2026

        IMPORTANT:
        TransactionNormalizer currently accepts date strings,
        not datetime objects. Returning a string here prevents
        the transaction date from becoming None.
        """

        if not value:
            return None

        match = re.match(
            r"^(\d{2}\s+[A-Za-z]{3}\s+\d{4})",
            value.strip(),
        )

        if not match:
            return None

        date_text = match.group(1)

        try:
            parsed_date = datetime.strptime(
                date_text,
                "%d %b %Y",
            )

            return parsed_date.strftime("%d-%m-%Y")

        except ValueError:
            return None

    # =========================================================
    # Amount Parsing
    # =========================================================

    @staticmethod
    def _parse_amount(value: str) -> float | None:
        """
        Parse a monetary value.

        Examples:

            '+30,000.00' -> 30000.00
            '-1,400.00'  -> -1400.00
            '30,164.83'  -> 30164.83
        """

        if not value:
            return None

        cleaned = (
            value
            .replace(",", "")
            .replace("₹", "")
            .strip()
        )

        try:
            return float(cleaned)
        except ValueError:
            return None

    # =========================================================
    # Balances
    # =========================================================

    def extract_balances(self):
        """
        Kotak's transaction table does not explicitly provide
        opening and closing balance fields.

        Therefore:

            opening balance =
                first transaction balance - first transaction amount

            closing balance =
                balance of the final transaction
        """

        rows = self._get_transaction_rows()

        if not rows:
            return

        # -----------------------------------------------------
        # Opening balance
        # -----------------------------------------------------

        first_signed_amount = self._parse_amount(rows[0][5])
        first_balance = self._parse_amount(rows[0][6])

        if (
            first_signed_amount is not None
            and first_balance is not None
        ):
            opening_balance = (
                first_balance - first_signed_amount
            )

            self.report.account.opening_balance = round(
                opening_balance,
                2,
            )

        # -----------------------------------------------------
        # Closing balance
        # -----------------------------------------------------

        last_balance = self._parse_amount(rows[-1][6])

        if last_balance is not None:
            self.report.account.closing_balance = round(
                last_balance,
                2,
            )

    # =========================================================
    # Transactions
    # =========================================================

    def extract_transactions(self):
        """
        Extract and normalize every Kotak transaction.
        """

        rows = self._get_transaction_rows()

        for row in rows:

            (
                transaction_number,
                transaction_date,
                value_date,
                description,
                reference_number,
                signed_amount,
                balance,
            ) = row

            # -------------------------------------------------
            # Amount
            # -------------------------------------------------

            signed_amount_value = self._parse_amount(
                signed_amount
            )

            balance_value = self._parse_amount(balance)

            if (
                signed_amount_value is None
                or balance_value is None
            ):
                continue

            # -------------------------------------------------
            # Debit / Credit
            # -------------------------------------------------

            if signed_amount_value >= 0:

                transaction_type = "CREDIT"
                amount = signed_amount_value

            else:

                transaction_type = "DEBIT"
                amount = abs(signed_amount_value)

            # -------------------------------------------------
            # Date
            # -------------------------------------------------

            parsed_date = self._parse_transaction_date(
                transaction_date
            )

            if parsed_date is None:
                continue

            # -------------------------------------------------
            # Description
            # -------------------------------------------------

            description = re.sub(
                r"\s+",
                " ",
                description,
            ).strip()

            # -------------------------------------------------
            # Reference
            # -------------------------------------------------

            reference_number = re.sub(
                r"\s+",
                " ",
                reference_number,
            ).strip()

            # -------------------------------------------------
            # Canonical transaction
            # -------------------------------------------------

            raw_transaction = {
                "date": parsed_date,
                "description": description,
                "type": transaction_type,
                "amount": amount,
                "balance": balance_value,
                "reference_number": reference_number,
                "cheque_number": "",
                "mode": "",
                "party": "",
                "bank": BankName.KOTAK.value,
            }

            self.add_transaction(raw_transaction)

    # =========================================================
    # Parse
    # =========================================================

    def parse(self):
        """
        Execute the complete Kotak statement parsing pipeline.
        """

        self.extract_account()
        self.extract_statement_period()
        self.extract_balances()
        self.extract_transactions()

        self.report.metadata["statement_type"] = "savings"
        self.report.metadata["bank"] = BankName.KOTAK.value

        return self.report
    
    