# # # # from core.statement_parser import StatementParser

# # # # parser = StatementParser(
# # # #     "data/parsed/adarsh-statement.md"
# # # # )

# # # # data = parser.parse()

# # # # print(data["transactions"][:])

# # # # parser.save(
# # # #     "data/structured/adarsh-statement.json"
# # # # )

# # # # # from core.analytics import AnalyticsEngine

# # # # # engine = AnalyticsEngine(
# # # # #     "data/structured/adarsh-statement.json"
# # # # # )

# # # # # print(engine.df.columns)
# # # # # print(engine.df.head())
# # # # # print(engine.df.dtypes)

# # # # # report = engine.generate_report()

# # # # # from pprint import pprint

# # # # # pprint(report)

# # # from core.statement_parser import StatementParser

# # # # Parse the markdown generated by LlamaParse
# # # parser = StatementParser(
# # #     "data/parsed/adarsh-statement.md"
# # # )

# # # # Parse all transactions
# # # data = parser.parse()

# # # # Print total transactions
# # # print(f"Total Transactions Parsed: {len(data['transactions'])}")

# # # # # Print first 3 transactions
# # # # for txn in data["transactions"][:3]:
# # # #     print(txn)

# # # # # Save the structured JSON
# # # # parser.save(
# # # #     "data/structured/adarsh-statement.json"
# # # # )

# # from pprint import pprint
# # from core.statement_parser import StatementParser
# # from core.analytics import AnalyticsEngine
# # from core.insights import InsightEngine
# # from core.risk_engine import RiskEngine

# # parser = StatementParser("data/parsed/adarsh-statement.md")
# # report = parser.parse()

# # print("Transactions Parsed:", report.total_transactions)
# # parser.save("data/structured/adarsh-statement.json")

# # from core.analytics import AnalyticsEngine
# # from core.insights import InsightEngine

# # analytics = AnalyticsEngine(report)
# # analytics_report = analytics.generate_report()

# # insights = InsightEngine(analytics_report)
# # insight_report = insights.generate_report()

# # risk = RiskEngine(analytics_report)
# # risk_report = risk.analyze()


# # pprint(insight_report)

# # from pprint import pprint

# # from core.statement_parser import StatementParser
# # from core.analytics import AnalyticsEngine
# # from core.insights import InsightEngine
# # from core.risk_engine import RiskEngine
# # from core.recommendation_engine import RecommendationEngine


# # parser = StatementParser("data/parsed/adarsh-statement.md")

# # report = parser.parse()

# # print("Transactions Parsed:", len(report.transactions))

# # parser.save("data/structured/adarsh-statement.json")


# # analytics = AnalyticsEngine(report)
# # report = analytics.generate_report()



# # insights = InsightEngine(report)
# # report = insights.generate_report()


# # risk = RiskEngine(report)
# # report = risk.analyze()

# # pprint(report.to_dict())


# from pprint import pprint

# from core.statement_parser import StatementParser
# from core.analytics import AnalyticsEngine
# from core.insights import InsightEngine
# from core.risk_engine import RiskEngine
# from core.recommendation_engine import RecommendationEngine


# def main():
#     # ==========================================================
#     # Parse Statement
#     # ==========================================================
#     parser = StatementParser("data/parsed/adarsh-statement.md")

#     report = parser.parse()

#     print(f"Transactions Parsed: {len(report.transactions)}")

#     # Save structured JSON
#     parser.save("data/structured/adarsh-statement.json")

#     # ==========================================================
#     # Analytics Engine
#     # ==========================================================
#     analytics = AnalyticsEngine(report)
#     report = analytics.generate_report()

#     # ==========================================================
#     # Insight Engine
#     # ==========================================================
#     insights = InsightEngine(report)
#     report = insights.generate_report()

#     # ==========================================================
#     # Risk Engine
#     # ==========================================================
#     risk = RiskEngine(report)
#     report = risk.analyze()

#     # ==========================================================
#     # Recommendation Engine
#     # ==========================================================
#     recommendation = RecommendationEngine(report)
#     report = recommendation.generate_report()

#     # ==========================================================
#     # Final Report
#     # ==========================================================
#     pprint(report.to_dict())


# if __name__ == "__main__":
#     main()

from core.statement_parser import StatementParser

parser = StatementParser(
    "Kotak-bank.md"
)

report = parser.parse()

print("Bank:", report.account.bank)
print("Period:", report.metadata.get("statement_period"))
print("Opening:", report.account.opening_balance)
print("Closing:", report.account.closing_balance)
print("Transactions:", len(report.transactions))
for txn in report.transactions[:5]:
    print(
        "DATE:", txn.date,
        "| TYPE:", txn.transaction_type,
        "| AMOUNT:", txn.amount,
        "| BALANCE:", txn.balance,
        "| REF:", txn.reference_number,
        "| PARTY:", txn.party,
        "| MODE:", txn.payment_mode,
    )

print("...")
txn = report.transactions[-1]

print(
    "DATE:", txn.date,
    "| TYPE:", txn.transaction_type,
    "| AMOUNT:", txn.amount,
    "| BALANCE:", txn.balance,
    "| REF:", txn.reference_number,
    "| PARTY:", txn.party,
    "| MODE:", txn.payment_mode,
)